language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements-test.txt"

# command to run tests
script: "python -m pytest test/test_pypeline.py"
