language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# Unfortunately ubuntu 12.04 doesn't have sufficiently recent leveldb
# packages in the repositories.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6 libgcc1 libstdc++6
  - dpkg -s libc6 libgcc1 libstdc++6
  - wget http://mirrors.kernel.org/ubuntu/pool/main/s/snappy/libsnappy1_1.0.5-2_i386.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/s/snappy/libsnappy-dev_1.0.5-2_i386.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/l/leveldb/libleveldb1_1.9.0-1_i386.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/l/leveldb/libleveldb-dev_1.9.0-1_i386.deb
  - sudo dpkg --install libsnappy1_1.0.5-2_i386.deb
  - sudo dpkg --install libsnappy-dev_1.0.5-2_i386.deb
  - sudo dpkg --install libleveldb1_1.9.0-1_i386.deb
  - sudo dpkg --install libleveldb-dev_1.9.0-1_i386.deb

install: "pip install -r requirements-test.txt"

script: "python -m pytest test/test_pypeline.py"
